### ISSUE TITLE
Assign different colors relating to article sources in Figure 12.

### ISSUE THREAD

**Issue by LucvandenBrand** [zeeguu-ecosystem/CHI18-Paper#23]

**Comment by LucvandenBrand** [comment]
@mircealungu How about this:
[PDF of improved Figure](https://github.com/zeeguu-ecosystem/CHI18-Paper/files/1596185/output.pdf)

This is the most detailed I could get, without manually checking and categorizing 300+ links.
Each category is based on the unique domain address associated with the category (some, like Le Monde, have a subdomain for particular kinds of content and are thus split into more than one category).

**Comment by mircealungu** [comment]
Hi @Lukeslux . And HNY! 

This looks cool! i think it might be confusing for the reader to see a different list of sources than in the previous two figures in the paper. We could explain, but we don't have space. Can you generate the same figure,  but for the sources listed in the other figures? 

<img width="426" alt="screen shot 2018-01-01 at 18 39 21" src="https://user-images.githubusercontent.com/464519/34469234-1f0451ee-ef23-11e7-8398-0bac3369bcea.png">

**Comment by LucvandenBrand** [comment]
Happy New Year to you too @mircealungu !

I merged some of the subdomains, and made the markers more distinct (the different colored circles seemed too difficult to discern). The new and improved plot can be seen 
[here](https://github.com/zeeguu-ecosystem/CHI18-Paper/files/1597405/output.pdf).

**Comment by mircealungu** [comment]
Awesome!
