### ISSUE TITLE
Latex will not properly compile

### ISSUE THREAD

**Issue by LucvandenBrand** [zeeguu-ecosystem/CHI18-Paper#4]
...at least, not for me.
Probably because there are missing files.

Errors:
- ! LaTeX Error: File `useful_defines.tex' not found.
- ! LaTeX Error: File `intro.tex' not found.
- In system.tex: ! Undefined control sequence. \ml (Maybe because useful defines is not there?)
- ! LaTeX Error: File `challenges.tex' not found.

**Comment by mircealungu** [comment]
thanks for the heads up.
added the missing files.
