### ISSUE TITLE
add sql queries and other scripts required for data analysis and chart extraction to version control

### ISSUE THREAD

**Issue by mircealungu** [zeeguu-ecosystem/CHI18-Paper#7]
probably best to create a separate folder for that

**Comment by LucvandenBrand** [comment]
Created a branch for it: [sql_queries](https://github.com/mircealungu/chi17/tree/sql_queries).
There should be a folder `scripts`, which contains the folder `queries`. I put the queries for my two included figures there.
@DanChirtoaca, @martinavagyan, feel free to put your queries there.
